@host=https://localhost:7256

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmNGRkYjQyNy03Zjk2LTQ1MWMtOTgyZi1kNmE4OTIxMjg5MTUiLCJnaXZlbl9uYW1lIjoiRGFuaWlsIiwiZmFtaWx5X25hbWUiOiJLbGp1a2luIiwianRpIjoiMmQxMmMxN2EtZTA5NS00ODAzLWJiODEtZjUzMmU2MWUwNzY4IiwiZXhwIjoxNzQwNjc4MTEwLCJpc3MiOiJSZXN0YXVyYW50IiwiYXVkIjoiUmVzdGF1cmFudCJ9.eFFG1x-JS8Cw4kJhsiRShv2e7VaaeIAKbSRYPsQc7rM