services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
        POSTGRES_DB: my_notes
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    volumes:
     - postgres-data:/var/lib/postgresql/data
    ports:
     - 5433:5432

volumes:
    postgres-data: